## Associative and Distributive 

In [1]:
import numpy as np

In [7]:
n = 10
a = np.random.randn(n)
b = np.random.randn(n)
c = np.random.randn(n)

In [9]:
# Distributive Property

res1 = np.dot(a,(b+c))
res2 = np.dot(a,b) + np.dot(a,c)

In [11]:
# Answer

res1 == res2

True

In [12]:
res1

2.065994106777301

In [13]:
res2

2.065994106777301

In [14]:
# Associative property

asres1 = np.dot(a, np.dot(b,c))
asres2 = np.dot(np.dot(a,b), c)

In [16]:
#Answer

print(asres1 == asres2)

[False False False False False False False False False False]


In [33]:
matrixA = np.random.randn(4,4)
matrixB = np.random.randn(4,4)

In [34]:
print(matrixA)
print(' ')
print(matrixB)

[[ 0.09377236  0.92046866  0.01335465  2.40665315]
 [ 0.14940278  0.5149734   1.92009843  0.68309542]
 [ 0.37102735 -0.30506417  0.70295749 -1.3358481 ]
 [ 0.46630818  1.19306019 -0.127914   -0.90193215]]
 
[[ 1.12884271 -0.04975282  0.83268308 -0.97024148]
 [ 0.62827203  0.33875083 -1.56860619 -1.08212191]
 [ 0.73981784 -2.39710697  0.43004872 -0.69511555]
 [-0.03147423  0.54784461 -0.63992814 -1.51808735]]


In [50]:
# Vector dot product in matrices

dps = np.zeros(4)

In [51]:
dps

array([0., 0., 0., 0.])

In [54]:
for i in range(4):
    dps[i] = np.dot(matrixA[:,i], matrixB[:,i])

In [55]:
dps

array([ 0.4595358 ,  1.51353479, -2.61659637, -0.77644665])

## Commutative

In [56]:
a = np.random.randn(10)
b = np.random.randn(10)

In [57]:
ab = np.dot(a,b)
ba = np.dot(b,a)

In [59]:
# Test

ab == ba

True

In [60]:
# Hence dot product is commutative